#!/bin/bash

# paragrep - jzu@free.fr 2011 - WTFPL

# grep patterns on paragraphs (separated by two line feeds)
# Returns whole paragraphs w/o linefeeds
# Multiple contiguous spaces reduced to a single one (useful for RFCs)
# Accepts all grep options
# Can read stdin
# If fed through stdin without a pattern, formats paragraphs on a single line

for i in $*
do
  echo $i | grep -q "^-"
  if [ $? = 0 ]
  then
    OPTS="$OPTS $i"
    shift
  fi
done

PATTERN="$1"
shift

if [ $# -eq 0 ] 
then
  sed -e ':a;N;$!ba;s/\([^\n]\)\n/\1 /g' \
      -e 's/  */ /g' \
  | grep $OPTS "$PATTERN"
else
  for i in $*
  do
    sed -e ':a;N;$!ba;s/\([^\n]\)\n/\1 /g' $i \
        -e 's/  */ /g' \
    | grep $OPTS "$PATTERN" \
    | sed -e "s/^/$i: /"
  done
fi

